name: qiniu_sdk_base
version: 0.2.3
homepage: https://github.com/qiniu/dart-sdk
description: The sdk basic of Qiniu products

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  crypto: ^3.0.0
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  dotenv: ^1.0.0
  test_coverage: "^0.5.0"
